// Code generated by errgen. DO NOT EDIT.

package case4

import (
	"encoding/json"
	"fmt"
	"github.com/myjupyter/errgen/test/case4_ambiguous/auth/v2"
	"github.com/myjupyter/errgen/test/case4_ambiguous/netpkg/v1"
	"log/slog"
)

// ConnectionError is a rich error type wrapping [ErrConnection]
type ConnectionError struct {
	Peer netpkg.Addr
}

// Error implements the error interface
func (e *ConnectionError) Error() string {
	return fmt.Sprintf("connection to %v failed", e.Peer)
}

// Is reports whether the target matches [ErrConnection]
func (e *ConnectionError) Is(target error) bool {
	return target == ErrConnection
}

// Unwrap returns the underlying error(s)
func (e *ConnectionError) Unwrap() error {
	return ErrConnection
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *ConnectionError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Any("peer", e.Peer),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *ConnectionError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error string      `json:"error"`
		Peer  netpkg.Addr `json:"peer"`
	}
	d := jsonError{Error: e.Error()}
	d.Peer = e.Peer
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *ConnectionError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Peer netpkg.Addr `json:"peer"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.Peer = d.Peer
	return nil
}

// NewConnectionError creates a new ConnectionError
func NewConnectionError(peer netpkg.Addr) *ConnectionError {
	e := &ConnectionError{
		Peer: peer,
	}
	e.onCreate()
	return e
}

// AuthError is a rich error type wrapping [ErrAuth]
type AuthError struct {
	Token auth.Token
}

// Error implements the error interface
func (e *AuthError) Error() string {
	return fmt.Sprintf("authentication failed for token %v", e.Token)
}

// Is reports whether the target matches [ErrAuth]
func (e *AuthError) Is(target error) bool {
	return target == ErrAuth
}

// Unwrap returns the underlying error(s)
func (e *AuthError) Unwrap() error {
	return ErrAuth
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *AuthError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Any("token", e.Token),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *AuthError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error string     `json:"error"`
		Token auth.Token `json:"token"`
	}
	d := jsonError{Error: e.Error()}
	d.Token = e.Token
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *AuthError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Token auth.Token `json:"token"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.Token = d.Token
	return nil
}

// NewAuthError creates a new AuthError
func NewAuthError(token auth.Token) *AuthError {
	e := &AuthError{
		Token: token,
	}
	e.onCreate()
	return e
}
