// Code generated by errgen. DO NOT EDIT.

package case4

import (
	"fmt"
	"github.com/myjupyter/errgen/test/case4_ambiguous/auth/v2"
	"github.com/myjupyter/errgen/test/case4_ambiguous/netpkg/v1"
)

// ConnectionError is a rich error type wrapping [ErrConnection]
type ConnectionError struct {
	Peer netpkg.Addr
}

// Error implements the error interface
func (e *ConnectionError) Error() string {
	return fmt.Sprintf("connection to %v failed", e.Peer)
}

// Is reports whether the target matches [ErrConnection]
func (e *ConnectionError) Is(target error) bool {
	return target == ErrConnection
}

// Unwrap returns the underlying error(s)
func (e *ConnectionError) Unwrap() error {
	return ErrConnection
}

// NewConnectionError creates a new ConnectionError
func NewConnectionError(peer netpkg.Addr) *ConnectionError {
	e := &ConnectionError{
		Peer: peer,
	}
	e.onCreate()
	return e
}

// AuthError is a rich error type wrapping [ErrAuth]
type AuthError struct {
	Token auth.Token
}

// Error implements the error interface
func (e *AuthError) Error() string {
	return fmt.Sprintf("authentication failed for token %v", e.Token)
}

// Is reports whether the target matches [ErrAuth]
func (e *AuthError) Is(target error) bool {
	return target == ErrAuth
}

// Unwrap returns the underlying error(s)
func (e *AuthError) Unwrap() error {
	return ErrAuth
}

// NewAuthError creates a new AuthError
func NewAuthError(token auth.Token) *AuthError {
	e := &AuthError{
		Token: token,
	}
	e.onCreate()
	return e
}
