// Code generated by errgen. Edit this file to add custom logic.
// This file will NOT be overwritten on subsequent runs.

package test

import (
	"fmt"
	"log/slog"
)

type Metric interface {
	Increment(string)
}

type noopMetric struct{}

func (noopMetric) Increment(string) {}

var metrics = noopMetric{}

// onCreate is a hook for user custom logic
// the code inside must not panic
func (e *ServiceUnavailableError) onCreate() {
	// on error emit produce error log with fields and metrics
	slog.Error("service", "error", e)
	metrics.Increment(fmt.Sprintf("service.%s.unavailable.error", e.Domain))
}
