// Code generated by errgen. DO NOT EDIT.

package test

import (
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
)

// ServiceUnavailableError is a rich error type wrapping [ErrServiceUnavailable]
type ServiceUnavailableError struct {
	Domain string
	Tags   []string
	Cause  error
}

// Error implements the error interface
func (e *ServiceUnavailableError) Error() string {
	return fmt.Sprintf("internal: service unavailable: [domain=\"%v\", tags=%v]; cause: %v", e.Domain, e.Tags, e.Cause)
}

// Is reports whether the target matches [ErrServiceUnavailable]
func (e *ServiceUnavailableError) Is(target error) bool {
	return target == ErrServiceUnavailable || target == ErrInternal
}

// Unwrap returns the underlying error(s)
func (e *ServiceUnavailableError) Unwrap() []error {
	return []error{e.Cause, ErrServiceUnavailable}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *ServiceUnavailableError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.String("domain", e.Domain),
		slog.Any("tags", e.Tags),
		slog.Any("cause", e.Cause),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *ServiceUnavailableError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error  string   `json:"error"`
		Domain string   `json:"domain"`
		Tags   []string `json:"tags"`
		Cause  string   `json:"cause,omitempty"`
	}
	d := jsonError{Error: e.Error()}
	d.Domain = e.Domain
	d.Tags = e.Tags
	if e.Cause != nil {
		d.Cause = e.Cause.Error()
	}
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *ServiceUnavailableError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Domain string   `json:"domain"`
		Tags   []string `json:"tags"`
		Cause  string   `json:"cause"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.Domain = d.Domain
	e.Tags = d.Tags
	if d.Cause != "" {
		e.Cause = errors.New(d.Cause)
	}
	return nil
}

// NewServiceUnavailableError creates a new ServiceUnavailableError
func NewServiceUnavailableError(domain string, tags []string, cause error) *ServiceUnavailableError {
	e := &ServiceUnavailableError{
		Domain: domain,
		Tags:   tags,
		Cause:  cause,
	}
	e.onCreate()
	return e
}
