// Code generated by errgen. DO NOT EDIT.

package test

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
)

// InternalError is a rich error type wrapping [ErrInternal]
type InternalError struct {
	Reason string
}

// Error implements the error interface
func (e *InternalError) Error() string {
	return fmt.Sprintf("internal error: reason is %v", e.Reason)
}

// Is reports whether the target matches [ErrInternal]
func (e *InternalError) Is(target error) bool {
	return target == ErrInternal
}

// Unwrap returns the underlying error(s)
func (e *InternalError) Unwrap() error {
	return ErrInternal
}

// StatusCode returns the HTTP status code for this error
func (e *InternalError) StatusCode() int {
	return http.StatusInternalServerError
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *InternalError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.String("reason", e.Reason),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *InternalError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error  string `json:"error"`
		Reason string `json:"reason"`
	}
	d := jsonError{Error: e.Error()}
	d.Reason = e.Reason
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *InternalError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Reason string `json:"reason"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.Reason = d.Reason
	return nil
}

// NewInternalError creates a new InternalError
func NewInternalError(reason string) *InternalError {
	e := &InternalError{
		Reason: reason,
	}
	e.onCreate()
	return e
}
