// Code generated by errgen. Edit this file to add custom logic.
// This file will NOT be overwritten on subsequent runs.

package test

// onCreate is a hook for user custom logic
// the code inside must not panic
func (e *InternalError) onCreate() {
	// put custom logic here
}
