// Code generated by errgen. DO NOT EDIT.

package model

import (
	"fmt"
	"log/slog"
)

// ParsingError is a rich error type wrapping [ErrParsing]
type ParsingError struct {
	WrappedError error
}

// Error implements the error interface
func (e *ParsingError) Error() string {
	return fmt.Sprintf("parsing: %v", e.WrappedError)
}

// Is reports whether the target matches [ErrParsing]
func (e *ParsingError) Is(target error) bool {
	return target == ErrParsing
}

// Unwrap returns the underlying error(s)
func (e *ParsingError) Unwrap() []error {
	return []error{e.WrappedError, ErrParsing}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *ParsingError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("wrappedError", e.WrappedError),
	)
}

// NewParsingError creates a new ParsingError
func NewParsingError(wrappedError error) *ParsingError {
	e := &ParsingError{
		WrappedError: wrappedError,
	}
	e.onCreate()
	return e
}

// GenerationError is a rich error type wrapping [ErrGeneration]
type GenerationError struct {
	WrappedError error
}

// Error implements the error interface
func (e *GenerationError) Error() string {
	return fmt.Sprintf("generator: %v", e.WrappedError)
}

// Is reports whether the target matches [ErrGeneration]
func (e *GenerationError) Is(target error) bool {
	return target == ErrGeneration
}

// Unwrap returns the underlying error(s)
func (e *GenerationError) Unwrap() []error {
	return []error{e.WrappedError, ErrGeneration}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *GenerationError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("wrappedError", e.WrappedError),
	)
}

// NewGenerationError creates a new GenerationError
func NewGenerationError(wrappedError error) *GenerationError {
	e := &GenerationError{
		WrappedError: wrappedError,
	}
	e.onCreate()
	return e
}

// ResolvingError is a rich error type wrapping [ErrResolving]
type ResolvingError struct {
	WrappedError error
}

// Error implements the error interface
func (e *ResolvingError) Error() string {
	return fmt.Sprintf("resolver: %v", e.WrappedError)
}

// Is reports whether the target matches [ErrResolving]
func (e *ResolvingError) Is(target error) bool {
	return target == ErrResolving
}

// Unwrap returns the underlying error(s)
func (e *ResolvingError) Unwrap() []error {
	return []error{e.WrappedError, ErrResolving}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *ResolvingError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("wrappedError", e.WrappedError),
	)
}

// NewResolvingError creates a new ResolvingError
func NewResolvingError(wrappedError error) *ResolvingError {
	e := &ResolvingError{
		WrappedError: wrappedError,
	}
	e.onCreate()
	return e
}

// ParsingAnnotationError is a rich error type wrapping [ErrParsingAnnotation]
type ParsingAnnotationError struct {
	ErrVarName   string
	WrappedError error
}

// Error implements the error interface
func (e *ParsingAnnotationError) Error() string {
	return fmt.Sprintf("error var '%v': %v", e.ErrVarName, e.WrappedError)
}

// Is reports whether the target matches [ErrParsingAnnotation]
func (e *ParsingAnnotationError) Is(target error) bool {
	return target == ErrParsingAnnotation
}

// Unwrap returns the underlying error(s)
func (e *ParsingAnnotationError) Unwrap() []error {
	return []error{e.WrappedError, ErrParsingAnnotation}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *ParsingAnnotationError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("errVarName", e.ErrVarName),
		slog.Any("wrappedError", e.WrappedError),
	)
}

// NewParsingAnnotationError creates a new ParsingAnnotationError
func NewParsingAnnotationError(errVarName string, wrappedError error) *ParsingAnnotationError {
	e := &ParsingAnnotationError{
		ErrVarName:   errVarName,
		WrappedError: wrappedError,
	}
	e.onCreate()
	return e
}

// ParsingFileError is a rich error type wrapping [ErrParsingFile]
type ParsingFileError struct {
	Filename     string
	WrappedError error
}

// Error implements the error interface
func (e *ParsingFileError) Error() string {
	return fmt.Sprintf("file '%v': %v", e.Filename, e.WrappedError)
}

// Is reports whether the target matches [ErrParsingFile]
func (e *ParsingFileError) Is(target error) bool {
	return target == ErrParsingFile
}

// Unwrap returns the underlying error(s)
func (e *ParsingFileError) Unwrap() []error {
	return []error{e.WrappedError, ErrParsingFile}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *ParsingFileError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("filename", e.Filename),
		slog.Any("wrappedError", e.WrappedError),
	)
}

// NewParsingFileError creates a new ParsingFileError
func NewParsingFileError(filename string, wrappedError error) *ParsingFileError {
	e := &ParsingFileError{
		Filename:     filename,
		WrappedError: wrappedError,
	}
	e.onCreate()
	return e
}

// ParsingInvalidErrorAnnotationError is a rich error type wrapping [ErrParsingInvalidErrorAnnotation]
type ParsingInvalidErrorAnnotationError struct {
	InvalidAnnotationText string
}

// Error implements the error interface
func (e *ParsingInvalidErrorAnnotationError) Error() string {
	return fmt.Sprintf("invalid error annotation '%v': expected: @Error(\"...\")", e.InvalidAnnotationText)
}

// Is reports whether the target matches [ErrParsingInvalidErrorAnnotation]
func (e *ParsingInvalidErrorAnnotationError) Is(target error) bool {
	return target == ErrParsingInvalidErrorAnnotation
}

// Unwrap returns the underlying error(s)
func (e *ParsingInvalidErrorAnnotationError) Unwrap() error {
	return ErrParsingInvalidErrorAnnotation
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *ParsingInvalidErrorAnnotationError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("invalidAnnotationText", e.InvalidAnnotationText),
	)
}

// NewParsingInvalidErrorAnnotationError creates a new ParsingInvalidErrorAnnotationError
func NewParsingInvalidErrorAnnotationError(invalidAnnotationText string) *ParsingInvalidErrorAnnotationError {
	e := &ParsingInvalidErrorAnnotationError{
		InvalidAnnotationText: invalidAnnotationText,
	}
	e.onCreate()
	return e
}

// ParsingInvalidVarAnnotationError is a rich error type wrapping [ErrParsingInvalidVarAnnotation]
type ParsingInvalidVarAnnotationError struct {
	InvalidAnnotationText string
	Message               string
}

// Error implements the error interface
func (e *ParsingInvalidVarAnnotationError) Error() string {
	return fmt.Sprintf("invalid var annotation '%v': %v", e.InvalidAnnotationText, e.Message)
}

// Is reports whether the target matches [ErrParsingInvalidVarAnnotation]
func (e *ParsingInvalidVarAnnotationError) Is(target error) bool {
	return target == ErrParsingInvalidVarAnnotation
}

// Unwrap returns the underlying error(s)
func (e *ParsingInvalidVarAnnotationError) Unwrap() error {
	return ErrParsingInvalidVarAnnotation
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *ParsingInvalidVarAnnotationError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("invalidAnnotationText", e.InvalidAnnotationText),
		slog.Any("message", e.Message),
	)
}

// NewParsingInvalidVarAnnotationError creates a new ParsingInvalidVarAnnotationError
func NewParsingInvalidVarAnnotationError(invalidAnnotationText string, message string) *ParsingInvalidVarAnnotationError {
	e := &ParsingInvalidVarAnnotationError{
		InvalidAnnotationText: invalidAnnotationText,
		Message:               message,
	}
	e.onCreate()
	return e
}

// GenInvalidTemplateError is a rich error type wrapping [ErrGenInvalidTemplate]
type GenInvalidTemplateError struct {
	TemplateName string
	WrappedError error
}

// Error implements the error interface
func (e *GenInvalidTemplateError) Error() string {
	return fmt.Sprintf("'%v' is invalid: %v", e.TemplateName, e.WrappedError)
}

// Is reports whether the target matches [ErrGenInvalidTemplate]
func (e *GenInvalidTemplateError) Is(target error) bool {
	return target == ErrGenInvalidTemplate
}

// Unwrap returns the underlying error(s)
func (e *GenInvalidTemplateError) Unwrap() []error {
	return []error{e.WrappedError, ErrGenInvalidTemplate}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *GenInvalidTemplateError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("templateName", e.TemplateName),
		slog.Any("wrappedError", e.WrappedError),
	)
}

// NewGenInvalidTemplateError creates a new GenInvalidTemplateError
func NewGenInvalidTemplateError(templateName string, wrappedError error) *GenInvalidTemplateError {
	e := &GenInvalidTemplateError{
		TemplateName: templateName,
		WrappedError: wrappedError,
	}
	e.onCreate()
	return e
}

// GenTemplateExecError is a rich error type wrapping [ErrGenTemplateExec]
type GenTemplateExecError struct {
	WrappedError error
}

// Error implements the error interface
func (e *GenTemplateExecError) Error() string {
	return fmt.Sprintf("template execution: %v", e.WrappedError)
}

// Is reports whether the target matches [ErrGenTemplateExec]
func (e *GenTemplateExecError) Is(target error) bool {
	return target == ErrGenTemplateExec
}

// Unwrap returns the underlying error(s)
func (e *GenTemplateExecError) Unwrap() []error {
	return []error{e.WrappedError, ErrGenTemplateExec}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *GenTemplateExecError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("wrappedError", e.WrappedError),
	)
}

// NewGenTemplateExecError creates a new GenTemplateExecError
func NewGenTemplateExecError(wrappedError error) *GenTemplateExecError {
	e := &GenTemplateExecError{
		WrappedError: wrappedError,
	}
	e.onCreate()
	return e
}

// GenCodeFormattingError is a rich error type wrapping [ErrGenCodeFormatting]
type GenCodeFormattingError struct {
	WrappedError error
}

// Error implements the error interface
func (e *GenCodeFormattingError) Error() string {
	return fmt.Sprintf("generated code formatting: %v", e.WrappedError)
}

// Is reports whether the target matches [ErrGenCodeFormatting]
func (e *GenCodeFormattingError) Is(target error) bool {
	return target == ErrGenCodeFormatting
}

// Unwrap returns the underlying error(s)
func (e *GenCodeFormattingError) Unwrap() []error {
	return []error{e.WrappedError, ErrGenCodeFormatting}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *GenCodeFormattingError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("wrappedError", e.WrappedError),
	)
}

// NewGenCodeFormattingError creates a new GenCodeFormattingError
func NewGenCodeFormattingError(wrappedError error) *GenCodeFormattingError {
	e := &GenCodeFormattingError{
		WrappedError: wrappedError,
	}
	e.onCreate()
	return e
}

// GenUnknownFieldError is a rich error type wrapping [ErrGenUnknownField]
type GenUnknownFieldError struct {
	UnknownField string
}

// Error implements the error interface
func (e *GenUnknownFieldError) Error() string {
	return fmt.Sprintf("no annotation found for '%v'", e.UnknownField)
}

// Is reports whether the target matches [ErrGenUnknownField]
func (e *GenUnknownFieldError) Is(target error) bool {
	return target == ErrGenUnknownField
}

// Unwrap returns the underlying error(s)
func (e *GenUnknownFieldError) Unwrap() error {
	return ErrGenUnknownField
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *GenUnknownFieldError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("unknownField", e.UnknownField),
	)
}

// NewGenUnknownFieldError creates a new GenUnknownFieldError
func NewGenUnknownFieldError(unknownField string) *GenUnknownFieldError {
	e := &GenUnknownFieldError{
		UnknownField: unknownField,
	}
	e.onCreate()
	return e
}

// GenErrDefError is a rich error type wrapping [ErrGenErrDef]
type GenErrDefError struct {
	ErrVarName   string
	WrappedError error
}

// Error implements the error interface
func (e *GenErrDefError) Error() string {
	return fmt.Sprintf("err var generation: '%v' build error: %v", e.ErrVarName, e.WrappedError)
}

// Is reports whether the target matches [ErrGenErrDef]
func (e *GenErrDefError) Is(target error) bool {
	return target == ErrGenErrDef
}

// Unwrap returns the underlying error(s)
func (e *GenErrDefError) Unwrap() []error {
	return []error{e.WrappedError, ErrGenErrDef}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *GenErrDefError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("errVarName", e.ErrVarName),
		slog.Any("wrappedError", e.WrappedError),
	)
}

// NewGenErrDefError creates a new GenErrDefError
func NewGenErrDefError(errVarName string, wrappedError error) *GenErrDefError {
	e := &GenErrDefError{
		ErrVarName:   errVarName,
		WrappedError: wrappedError,
	}
	e.onCreate()
	return e
}

// PackageNotFoundError is a rich error type wrapping [ErrPackageNotFound]
type PackageNotFoundError struct {
	PackageName string
	ModulePath  string
}

// Error implements the error interface
func (e *PackageNotFoundError) Error() string {
	return fmt.Sprintf("resolver: package '%v' not found in module %v", e.PackageName, e.ModulePath)
}

// Is reports whether the target matches [ErrPackageNotFound]
func (e *PackageNotFoundError) Is(target error) bool {
	return target == ErrPackageNotFound
}

// Unwrap returns the underlying error(s)
func (e *PackageNotFoundError) Unwrap() error {
	return ErrPackageNotFound
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *PackageNotFoundError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("packageName", e.PackageName),
		slog.Any("modulePath", e.ModulePath),
	)
}

// NewPackageNotFoundError creates a new PackageNotFoundError
func NewPackageNotFoundError(packageName string, modulePath string) *PackageNotFoundError {
	e := &PackageNotFoundError{
		PackageName: packageName,
		ModulePath:  modulePath,
	}
	e.onCreate()
	return e
}

// AmbiguousPackageError is a rich error type wrapping [ErrAmbiguousPackage]
type AmbiguousPackageError struct {
	PackageName string
	Locations   string
}

// Error implements the error interface
func (e *AmbiguousPackageError) Error() string {
	return fmt.Sprintf("resolver: package name '%v' is ambiguous, found in:\n  %v\nuse -m flag to specify the import path", e.PackageName, e.Locations)
}

// Is reports whether the target matches [ErrAmbiguousPackage]
func (e *AmbiguousPackageError) Is(target error) bool {
	return target == ErrAmbiguousPackage
}

// Unwrap returns the underlying error(s)
func (e *AmbiguousPackageError) Unwrap() error {
	return ErrAmbiguousPackage
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *AmbiguousPackageError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("packageName", e.PackageName),
		slog.Any("locations", e.Locations),
	)
}

// NewAmbiguousPackageError creates a new AmbiguousPackageError
func NewAmbiguousPackageError(packageName string, locations string) *AmbiguousPackageError {
	e := &AmbiguousPackageError{
		PackageName: packageName,
		Locations:   locations,
	}
	e.onCreate()
	return e
}

// GoModNotFoundError is a rich error type wrapping [ErrGoModNotFound]
type GoModNotFoundError struct {
}

// Error implements the error interface
func (e *GoModNotFoundError) Error() string {
	return fmt.Sprintf("resolver: go.mod not found")
}

// Is reports whether the target matches [ErrGoModNotFound]
func (e *GoModNotFoundError) Is(target error) bool {
	return target == ErrGoModNotFound
}

// Unwrap returns the underlying error(s)
func (e *GoModNotFoundError) Unwrap() error {
	return ErrGoModNotFound
}

// NewGoModNotFoundError creates a new GoModNotFoundError
func NewGoModNotFoundError() *GoModNotFoundError {
	e := &GoModNotFoundError{}
	e.onCreate()
	return e
}

// NoModuleDirectiveError is a rich error type wrapping [ErrNoModuleDirective]
type NoModuleDirectiveError struct {
}

// Error implements the error interface
func (e *NoModuleDirectiveError) Error() string {
	return fmt.Sprintf("resolver: no module directive in go.mod")
}

// Is reports whether the target matches [ErrNoModuleDirective]
func (e *NoModuleDirectiveError) Is(target error) bool {
	return target == ErrNoModuleDirective
}

// Unwrap returns the underlying error(s)
func (e *NoModuleDirectiveError) Unwrap() error {
	return ErrNoModuleDirective
}

// NewNoModuleDirectiveError creates a new NoModuleDirectiveError
func NewNoModuleDirectiveError() *NoModuleDirectiveError {
	e := &NoModuleDirectiveError{}
	e.onCreate()
	return e
}
