// Code generated by errgen. DO NOT EDIT.

package case7

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
)

// NotFoundError is a rich error type wrapping [ErrNotFound]
type NotFoundError struct {
	Message string
}

// Error implements the error interface
func (e *NotFoundError) Error() string {
	return fmt.Sprintf("not found: %v", e.Message)
}

// Is reports whether the target matches [ErrNotFound]
func (e *NotFoundError) Is(target error) bool {
	return target == ErrNotFound
}

// Unwrap returns the underlying error(s)
func (e *NotFoundError) Unwrap() error {
	return ErrNotFound
}

// StatusCode returns the HTTP status code for this error
func (e *NotFoundError) StatusCode() int {
	return http.StatusNotFound
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *NotFoundError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Any("message", e.Message),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *NotFoundError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error   string `json:"error"`
		Message string `json:"message"`
	}
	d := jsonError{Error: e.Error()}
	d.Message = e.Message
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *NotFoundError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Message string `json:"message"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.Message = d.Message
	return nil
}

// NewNotFoundError creates a new NotFoundError
func NewNotFoundError(message string) *NotFoundError {
	e := &NotFoundError{
		Message: message,
	}
	e.onCreate()
	return e
}

// BadRequestError is a rich error type wrapping [ErrBadRequest]
type BadRequestError struct {
	Field string
}

// Error implements the error interface
func (e *BadRequestError) Error() string {
	return fmt.Sprintf("bad request: invalid field '%v'", e.Field)
}

// Is reports whether the target matches [ErrBadRequest]
func (e *BadRequestError) Is(target error) bool {
	return target == ErrBadRequest
}

// Unwrap returns the underlying error(s)
func (e *BadRequestError) Unwrap() error {
	return ErrBadRequest
}

// StatusCode returns the HTTP status code for this error
func (e *BadRequestError) StatusCode() int {
	return http.StatusBadRequest
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *BadRequestError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Any("field", e.Field),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *BadRequestError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error string `json:"error"`
		Field string `json:"field"`
	}
	d := jsonError{Error: e.Error()}
	d.Field = e.Field
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *BadRequestError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Field string `json:"field"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.Field = d.Field
	return nil
}

// NewBadRequestError creates a new BadRequestError
func NewBadRequestError(field string) *BadRequestError {
	e := &BadRequestError{
		Field: field,
	}
	e.onCreate()
	return e
}

// InternalError is a rich error type wrapping [ErrInternal]
type InternalError struct {
	Message string
}

// Error implements the error interface
func (e *InternalError) Error() string {
	return fmt.Sprintf("internal: %v", e.Message)
}

// Is reports whether the target matches [ErrInternal]
func (e *InternalError) Is(target error) bool {
	return target == ErrInternal
}

// Unwrap returns the underlying error(s)
func (e *InternalError) Unwrap() error {
	return ErrInternal
}

// StatusCode returns the HTTP status code for this error
func (e *InternalError) StatusCode() int {
	return 500
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *InternalError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Any("message", e.Message),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *InternalError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error   string `json:"error"`
		Message string `json:"message"`
	}
	d := jsonError{Error: e.Error()}
	d.Message = e.Message
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *InternalError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Message string `json:"message"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.Message = d.Message
	return nil
}

// NewInternalError creates a new InternalError
func NewInternalError(message string) *InternalError {
	e := &InternalError{
		Message: message,
	}
	e.onCreate()
	return e
}

// GenericError is a rich error type wrapping [ErrGeneric]
type GenericError struct {
	Reason string
}

// Error implements the error interface
func (e *GenericError) Error() string {
	return ErrGeneric.Error()
}

// Is reports whether the target matches [ErrGeneric]
func (e *GenericError) Is(target error) bool {
	return target == ErrGeneric
}

// Unwrap returns the underlying error(s)
func (e *GenericError) Unwrap() error {
	return ErrGeneric
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *GenericError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Any("reason", e.Reason),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *GenericError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error  string `json:"error"`
		Reason string `json:"reason"`
	}
	d := jsonError{Error: e.Error()}
	d.Reason = e.Reason
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *GenericError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Reason string `json:"reason"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.Reason = d.Reason
	return nil
}

// NewGenericError creates a new GenericError
func NewGenericError(reason string) *GenericError {
	e := &GenericError{
		Reason: reason,
	}
	e.onCreate()
	return e
}
