// Code generated by errgen. DO NOT EDIT.

package main

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"time"

	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
)

// InternalError is a rich error type wrapping [ErrInternal]
type InternalError struct {
	StringField      string
	Int64Field       int64
	IntField         int
	Uint64Field      uint64
	UintField        uint
	UintptrField     uintptr
	Float64Field     float64
	BoolField        bool
	TimeField        time.Time
	DurationField    time.Duration
	IntSliceField    []int
	ObjectSliceField []Object
	MapType          map[string]string
}

// Error implements the error interface
func (e *InternalError) Error() string {
	return ErrInternal.Error()
}

// Is reports whether the target matches [ErrInternal]
func (e *InternalError) Is(target error) bool {
	return target == ErrInternal
}

// Unwrap returns the underlying error(s)
func (e *InternalError) Unwrap() error {
	return ErrInternal
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *InternalError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.String("stringField", e.StringField),
		slog.Int64("int64Field", e.Int64Field),
		slog.Int("intField", e.IntField),
		slog.Uint64("uint64Field", e.Uint64Field),
		slog.Uint64("uintField", uint64(e.UintField)),
		slog.Uint64("uintptrField", uint64(e.UintptrField)),
		slog.Float64("float64Field", e.Float64Field),
		slog.Bool("boolField", e.BoolField),
		slog.Time("timeField", e.TimeField),
		slog.Duration("durationField", e.DurationField),
		slog.Any("intSliceField", e.IntSliceField),
		slog.Any("objectSliceField", e.ObjectSliceField),
		slog.Any("mapType", e.MapType),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *InternalError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error            string            `json:"error"`
		StringField      string            `json:"stringField"`
		Int64Field       int64             `json:"int64Field"`
		IntField         int               `json:"intField"`
		Uint64Field      uint64            `json:"uint64Field"`
		UintField        uint              `json:"uintField"`
		UintptrField     uintptr           `json:"uintptrField"`
		Float64Field     float64           `json:"float64Field"`
		BoolField        bool              `json:"boolField"`
		TimeField        time.Time         `json:"timeField"`
		DurationField    time.Duration     `json:"durationField"`
		IntSliceField    []int             `json:"intSliceField"`
		ObjectSliceField []Object          `json:"objectSliceField"`
		MapType          map[string]string `json:"mapType"`
	}
	d := jsonError{Error: e.Error()}
	d.StringField = e.StringField
	d.Int64Field = e.Int64Field
	d.IntField = e.IntField
	d.Uint64Field = e.Uint64Field
	d.UintField = e.UintField
	d.UintptrField = e.UintptrField
	d.Float64Field = e.Float64Field
	d.BoolField = e.BoolField
	d.TimeField = e.TimeField
	d.DurationField = e.DurationField
	d.IntSliceField = e.IntSliceField
	d.ObjectSliceField = e.ObjectSliceField
	d.MapType = e.MapType
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *InternalError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		StringField      string            `json:"stringField"`
		Int64Field       int64             `json:"int64Field"`
		IntField         int               `json:"intField"`
		Uint64Field      uint64            `json:"uint64Field"`
		UintField        uint              `json:"uintField"`
		UintptrField     uintptr           `json:"uintptrField"`
		Float64Field     float64           `json:"float64Field"`
		BoolField        bool              `json:"boolField"`
		TimeField        time.Time         `json:"timeField"`
		DurationField    time.Duration     `json:"durationField"`
		IntSliceField    []int             `json:"intSliceField"`
		ObjectSliceField []Object          `json:"objectSliceField"`
		MapType          map[string]string `json:"mapType"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.StringField = d.StringField
	e.Int64Field = d.Int64Field
	e.IntField = d.IntField
	e.Uint64Field = d.Uint64Field
	e.UintField = d.UintField
	e.UintptrField = d.UintptrField
	e.Float64Field = d.Float64Field
	e.BoolField = d.BoolField
	e.TimeField = d.TimeField
	e.DurationField = d.DurationField
	e.IntSliceField = d.IntSliceField
	e.ObjectSliceField = d.ObjectSliceField
	e.MapType = d.MapType
	return nil
}

// MarshalLogObject implements [zapcore.ObjectMarshaler] for zap structured logging
func (e *InternalError) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	enc.AddString("error", e.Error())
	enc.AddString("stringField", e.StringField)
	enc.AddInt64("int64Field", e.Int64Field)
	enc.AddInt("intField", e.IntField)
	enc.AddUint64("uint64Field", e.Uint64Field)
	enc.AddUint("uintField", e.UintField)
	enc.AddUintptr("uintptrField", e.UintptrField)
	enc.AddFloat64("float64Field", e.Float64Field)
	enc.AddBool("boolField", e.BoolField)
	enc.AddTime("timeField", e.TimeField)
	enc.AddDuration("durationField", e.DurationField)
	zap.Any("intSliceField", e.IntSliceField).AddTo(enc)
	zap.Any("objectSliceField", e.ObjectSliceField).AddTo(enc)
	zap.Any("mapType", e.MapType).AddTo(enc)
	return nil
}

// NewInternalError creates a new InternalError
func NewInternalError(stringField string, int64Field int64, intField int, uint64Field uint64, uintField uint, uintptrField uintptr, float64Field float64, boolField bool, timeField time.Time, durationField time.Duration, intSliceField []int, objectSliceField []Object, mapType map[string]string) *InternalError {
	e := &InternalError{
		StringField:      stringField,
		Int64Field:       int64Field,
		IntField:         intField,
		Uint64Field:      uint64Field,
		UintField:        uintField,
		UintptrField:     uintptrField,
		Float64Field:     float64Field,
		BoolField:        boolField,
		TimeField:        timeField,
		DurationField:    durationField,
		IntSliceField:    intSliceField,
		ObjectSliceField: objectSliceField,
		MapType:          mapType,
	}
	return e
}

// EntityNotFoundError is a rich error type wrapping [ErrEntityNotFound]
type EntityNotFoundError struct {
	EntityType string
	ID         int
}

// Error implements the error interface
func (e *EntityNotFoundError) Error() string {
	return fmt.Sprintf("'%v' with ID %v not found", e.EntityType, e.ID)
}

// Is reports whether the target matches [ErrEntityNotFound]
func (e *EntityNotFoundError) Is(target error) bool {
	return target == ErrEntityNotFound
}

// Unwrap returns the underlying error(s)
func (e *EntityNotFoundError) Unwrap() error {
	return ErrEntityNotFound
}

// StatusCode returns the HTTP status code for this error
func (e *EntityNotFoundError) StatusCode() int {
	return 404
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *EntityNotFoundError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.String("entityType", e.EntityType),
		slog.Int("iD", e.ID),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *EntityNotFoundError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error      string `json:"error"`
		EntityType string `json:"entityType"`
		ID         int    `json:"iD"`
	}
	d := jsonError{Error: e.Error()}
	d.EntityType = e.EntityType
	d.ID = e.ID
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *EntityNotFoundError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		EntityType string `json:"entityType"`
		ID         int    `json:"iD"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.EntityType = d.EntityType
	e.ID = d.ID
	return nil
}

// MarshalLogObject implements [zapcore.ObjectMarshaler] for zap structured logging
func (e *EntityNotFoundError) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	enc.AddString("error", e.Error())
	enc.AddString("entityType", e.EntityType)
	enc.AddInt("iD", e.ID)
	return nil
}

// NewEntityNotFoundError creates a new EntityNotFoundError
func NewEntityNotFoundError(entityType string, iD int) *EntityNotFoundError {
	e := &EntityNotFoundError{
		EntityType: entityType,
		ID:         iD,
	}
	return e
}
