// Code generated by errgen. Edit this file to add custom logic.
// This file will NOT be overwritten on subsequent runs.

package case1

import "fmt"

// onCreate is a hook for user custom logic
// the code inside must not panic
func (e *ApplicationError) onCreate() {
	fmt.Println("application error")
}

// onCreate is a hook for user custom logic
// the code inside must not panic
func (e *NotFoundError) onCreate() {
	fmt.Println("not found error")
}

// onCreate is a hook for user custom logic
// the code inside must not panic
func (e *InternalError) onCreate() {
	fmt.Println("internal error")
}

// onCreate is a hook for user custom logic
// the code inside must not panic
func (e *TimeoutError) onCreate() {
	fmt.Println("timeout error")
}

// onCreate is a hook for user custom logic
// the code inside must not panic
func (e *ValidationError) onCreate() {
	// put custom logic here
}

// onCreate is a hook for user custom logic
// the code inside must not panic
func (e *InvalidErrError) onCreate() {
	// put custom logic here
}
