// Code generated by errgen. DO NOT EDIT.

package case1

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"time"
)

// ApplicationError is a rich error type wrapping [ErrApplication]
type ApplicationError struct {
	Code    int
	Message string
	ErrTime time.Time
	Ctx     context.Context
}

// Error implements the error interface
func (e *ApplicationError) Error() string {
	return fmt.Sprintf("error code %v: %v", e.Code, e.Message)
}

// Is reports whether the target matches [ErrApplication]
func (e *ApplicationError) Is(target error) bool {
	return target == ErrApplication
}

// Unwrap returns the underlying error(s)
func (e *ApplicationError) Unwrap() error {
	return ErrApplication
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *ApplicationError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Any("code", e.Code),
		slog.Any("message", e.Message),
		slog.Any("errTime", e.ErrTime),
		slog.Any("ctx", e.Ctx),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *ApplicationError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error   string          `json:"error"`
		Code    int             `json:"code"`
		Message string          `json:"message"`
		ErrTime time.Time       `json:"errTime"`
		Ctx     context.Context `json:"ctx"`
	}
	d := jsonError{Error: e.Error()}
	d.Code = e.Code
	d.Message = e.Message
	d.ErrTime = e.ErrTime
	d.Ctx = e.Ctx
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *ApplicationError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Code    int             `json:"code"`
		Message string          `json:"message"`
		ErrTime time.Time       `json:"errTime"`
		Ctx     context.Context `json:"ctx"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.Code = d.Code
	e.Message = d.Message
	e.ErrTime = d.ErrTime
	e.Ctx = d.Ctx
	return nil
}

// NewApplicationError creates a new ApplicationError
func NewApplicationError(code int, message string, errTime time.Time, ctx context.Context) *ApplicationError {
	e := &ApplicationError{
		Code:    code,
		Message: message,
		ErrTime: errTime,
		Ctx:     ctx,
	}
	e.onCreate()
	return e
}

// NotFoundError is a rich error type wrapping [ErrNotFound]
type NotFoundError struct {
	Reason string
}

// Error implements the error interface
func (e *NotFoundError) Error() string {
	return ErrNotFound.Error()
}

// Is reports whether the target matches [ErrNotFound]
func (e *NotFoundError) Is(target error) bool {
	return target == ErrNotFound
}

// Unwrap returns the underlying error(s)
func (e *NotFoundError) Unwrap() error {
	return ErrNotFound
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *NotFoundError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Any("reason", e.Reason),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *NotFoundError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error  string `json:"error"`
		Reason string `json:"reason"`
	}
	d := jsonError{Error: e.Error()}
	d.Reason = e.Reason
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *NotFoundError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Reason string `json:"reason"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.Reason = d.Reason
	return nil
}

// NewNotFoundError creates a new NotFoundError
func NewNotFoundError(reason string) *NotFoundError {
	e := &NotFoundError{
		Reason: reason,
	}
	e.onCreate()
	return e
}

// InternalError is a rich error type wrapping [ErrInternal]
type InternalError struct {
	WrappedError error
}

// Error implements the error interface
func (e *InternalError) Error() string {
	return fmt.Sprintf("internal failure: %v", e.WrappedError)
}

// Is reports whether the target matches [ErrInternal]
func (e *InternalError) Is(target error) bool {
	return target == ErrInternal
}

// Unwrap returns the underlying error(s)
func (e *InternalError) Unwrap() []error {
	return []error{e.WrappedError, ErrInternal}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *InternalError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Any("wrappedError", e.WrappedError),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *InternalError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error        string `json:"error"`
		WrappedError string `json:"wrappedError,omitempty"`
	}
	d := jsonError{Error: e.Error()}
	if e.WrappedError != nil {
		d.WrappedError = e.WrappedError.Error()
	}
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *InternalError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		WrappedError string `json:"wrappedError"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	if d.WrappedError != "" {
		e.WrappedError = errors.New(d.WrappedError)
	}
	return nil
}

// NewInternalError creates a new InternalError
func NewInternalError(wrappedError error) *InternalError {
	e := &InternalError{
		WrappedError: wrappedError,
	}
	e.onCreate()
	return e
}

// TimeoutError is a rich error type wrapping [ErrTimeout]
type TimeoutError struct {
	Timeout  int
	Endpoint string
}

// Error implements the error interface
func (e *TimeoutError) Error() string {
	return fmt.Sprintf("request to '%v' timed out after %v ms", e.Timeout, e.Endpoint)
}

// Is reports whether the target matches [ErrTimeout]
func (e *TimeoutError) Is(target error) bool {
	return target == ErrTimeout
}

// Unwrap returns the underlying error(s)
func (e *TimeoutError) Unwrap() error {
	return ErrTimeout
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *TimeoutError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Any("timeout", e.Timeout),
		slog.Any("endpoint", e.Endpoint),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *TimeoutError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error    string `json:"error"`
		Timeout  int    `json:"timeout"`
		Endpoint string `json:"endpoint"`
	}
	d := jsonError{Error: e.Error()}
	d.Timeout = e.Timeout
	d.Endpoint = e.Endpoint
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *TimeoutError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Timeout  int    `json:"timeout"`
		Endpoint string `json:"endpoint"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.Timeout = d.Timeout
	e.Endpoint = d.Endpoint
	return nil
}

// NewTimeoutError creates a new TimeoutError
func NewTimeoutError(timeout int, endpoint string) *TimeoutError {
	e := &TimeoutError{
		Timeout:  timeout,
		Endpoint: endpoint,
	}
	e.onCreate()
	return e
}

// ValidationError is a rich error type wrapping [ErrValidation]
type ValidationError struct {
}

// Error implements the error interface
func (e *ValidationError) Error() string {
	return fmt.Sprintf("HTTP error: invalid status code")
}

// Is reports whether the target matches [ErrValidation]
func (e *ValidationError) Is(target error) bool {
	return target == ErrValidation
}

// Unwrap returns the underlying error(s)
func (e *ValidationError) Unwrap() error {
	return ErrValidation
}

// NewValidationError creates a new ValidationError
func NewValidationError() *ValidationError {
	e := &ValidationError{}
	e.onCreate()
	return e
}

// InvalidErrError is a rich error type wrapping [InvalidErr]
type InvalidErrError struct {
	Code   int
	Domain string
}

// Error implements the error interface
func (e *InvalidErrError) Error() string {
	return fmt.Sprintf("invalid argument: code=%v, domain=%v", e.Code, e.Domain)
}

// Is reports whether the target matches [InvalidErr]
func (e *InvalidErrError) Is(target error) bool {
	return target == InvalidErr
}

// Unwrap returns the underlying error(s)
func (e *InvalidErrError) Unwrap() error {
	return InvalidErr
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *InvalidErrError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Any("code", e.Code),
		slog.Any("domain", e.Domain),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *InvalidErrError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error  string `json:"error"`
		Code   int    `json:"code"`
		Domain string `json:"domain"`
	}
	d := jsonError{Error: e.Error()}
	d.Code = e.Code
	d.Domain = e.Domain
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *InvalidErrError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Code   int    `json:"code"`
		Domain string `json:"domain"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.Code = d.Code
	e.Domain = d.Domain
	return nil
}

// NewInvalidErrError creates a new InvalidErrError
func NewInvalidErrError(code int, domain string) *InvalidErrError {
	e := &InvalidErrError{
		Code:   code,
		Domain: domain,
	}
	e.onCreate()
	return e
}
