// Code generated by errgen. DO NOT EDIT.

package case1

import (
	"fmt"
)

// ApplicationError is a rich error type wrapping [ErrApplication]
type ApplicationError struct {
	Code    int
	Message string
}

// Error implements the error interface
func (e *ApplicationError) Error() string {
	return fmt.Sprintf("error code %v: %v", e.Code, e.Message)
}

// Is reports whether the target matches [ErrApplication]
func (e *ApplicationError) Is(target error) bool {
	return target == ErrApplication
}

// Unwrap returns the underlying error(s)
func (e *ApplicationError) Unwrap() error {
	return ErrApplication
}

// NewApplicationError creates a new ApplicationError
func NewApplicationError(code int, message string) *ApplicationError {
	e := &ApplicationError{
		Code:    code,
		Message: message,
	}
	e.onCreate()
	return e
}

// NotFoundError is a rich error type wrapping [ErrNotFound]
type NotFoundError struct {
	Reason string
}

// Error implements the error interface
func (e *NotFoundError) Error() string {
	return ErrNotFound.Error()
}

// Is reports whether the target matches [ErrNotFound]
func (e *NotFoundError) Is(target error) bool {
	return target == ErrNotFound
}

// Unwrap returns the underlying error(s)
func (e *NotFoundError) Unwrap() error {
	return ErrNotFound
}

// NewNotFoundError creates a new NotFoundError
func NewNotFoundError(reason string) *NotFoundError {
	e := &NotFoundError{
		Reason: reason,
	}
	e.onCreate()
	return e
}

// InternalError is a rich error type wrapping [ErrInternal]
type InternalError struct {
	WrappedError error
}

// Error implements the error interface
func (e *InternalError) Error() string {
	return fmt.Sprintf("internal failure: %v", e.WrappedError)
}

// Is reports whether the target matches [ErrInternal]
func (e *InternalError) Is(target error) bool {
	return target == ErrInternal
}

// Unwrap returns the underlying error(s)
func (e *InternalError) Unwrap() []error {
	return []error{e.WrappedError, ErrInternal}
}

// NewInternalError creates a new InternalError
func NewInternalError(wrappedError error) *InternalError {
	e := &InternalError{
		WrappedError: wrappedError,
	}
	e.onCreate()
	return e
}

// TimeoutError is a rich error type wrapping [ErrTimeout]
type TimeoutError struct {
	Timeout  int
	Endpoint string
}

// Error implements the error interface
func (e *TimeoutError) Error() string {
	return fmt.Sprintf("request to '%v' timed out after %v ms", e.Timeout, e.Endpoint)
}

// Is reports whether the target matches [ErrTimeout]
func (e *TimeoutError) Is(target error) bool {
	return target == ErrTimeout
}

// Unwrap returns the underlying error(s)
func (e *TimeoutError) Unwrap() error {
	return ErrTimeout
}

// NewTimeoutError creates a new TimeoutError
func NewTimeoutError(timeout int, endpoint string) *TimeoutError {
	e := &TimeoutError{
		Timeout:  timeout,
		Endpoint: endpoint,
	}
	e.onCreate()
	return e
}

// ValidationError is a rich error type wrapping [ErrValidation]
type ValidationError struct {
}

// Error implements the error interface
func (e *ValidationError) Error() string {
	return fmt.Sprintf("HTTP error: invalid status code")
}

// Is reports whether the target matches [ErrValidation]
func (e *ValidationError) Is(target error) bool {
	return target == ErrValidation
}

// Unwrap returns the underlying error(s)
func (e *ValidationError) Unwrap() error {
	return ErrValidation
}

// NewValidationError creates a new ValidationError
func NewValidationError() *ValidationError {
	e := &ValidationError{}
	e.onCreate()
	return e
}
