// Code generated by errgen. Edit this file to add custom logic.
// This file will NOT be overwritten on subsequent runs.

package case2

// onCreate is a hook for user custom logic
// the code inside must not panic
func (e *ProcessingError) onCreate() {
	// put custom logic here
}

// onCreate is a hook for user custom logic
// the code inside must not panic
func (e *MultiImportError) onCreate() {
	// put custom logic here
}
