// Code generated by errgen. DO NOT EDIT.

package case2

import (
	"encoding/json"
	"fmt"
	"github.com/myjupyter/errgen/test/case2_imports/custom1"
	"github.com/myjupyter/errgen/test/case2_imports/custom2"
	"github.com/myjupyter/errgen/test/case2_imports/custom3"
	"log/slog"
)

// ProcessingError is a rich error type wrapping [ErrProcessing]
type ProcessingError struct {
	Item    custom1.Item
	Mapping map[string]custom2.Details
	Tags    []custom3.Tag
}

// Error implements the error interface
func (e *ProcessingError) Error() string {
	return fmt.Sprintf("processing: item=%v, mapping=%v, tags=%v", e.Item, e.Mapping, e.Tags)
}

// Is reports whether the target matches [ErrProcessing]
func (e *ProcessingError) Is(target error) bool {
	return target == ErrProcessing
}

// Unwrap returns the underlying error(s)
func (e *ProcessingError) Unwrap() error {
	return ErrProcessing
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *ProcessingError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Any("item", e.Item),
		slog.Any("mapping", e.Mapping),
		slog.Any("tags", e.Tags),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *ProcessingError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error   string                     `json:"error"`
		Item    custom1.Item               `json:"item"`
		Mapping map[string]custom2.Details `json:"mapping"`
		Tags    []custom3.Tag              `json:"tags"`
	}
	d := jsonError{Error: e.Error()}
	d.Item = e.Item
	d.Mapping = e.Mapping
	d.Tags = e.Tags
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *ProcessingError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Item    custom1.Item               `json:"item"`
		Mapping map[string]custom2.Details `json:"mapping"`
		Tags    []custom3.Tag              `json:"tags"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.Item = d.Item
	e.Mapping = d.Mapping
	e.Tags = d.Tags
	return nil
}

// NewProcessingError creates a new ProcessingError
func NewProcessingError(item custom1.Item, mapping map[string]custom2.Details, tags []custom3.Tag) *ProcessingError {
	e := &ProcessingError{
		Item:    item,
		Mapping: mapping,
		Tags:    tags,
	}
	e.onCreate()
	return e
}

// MultiImportError is a rich error type wrapping [ErrMultiImport]
type MultiImportError struct {
	Ptr         *custom1.Item
	DetailSlice []custom2.Details
	TagMap      map[string]custom3.Tag
}

// Error implements the error interface
func (e *MultiImportError) Error() string {
	return ErrMultiImport.Error()
}

// Is reports whether the target matches [ErrMultiImport]
func (e *MultiImportError) Is(target error) bool {
	return target == ErrMultiImport
}

// Unwrap returns the underlying error(s)
func (e *MultiImportError) Unwrap() error {
	return ErrMultiImport
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *MultiImportError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Any("ptr", e.Ptr),
		slog.Any("detailSlice", e.DetailSlice),
		slog.Any("tagMap", e.TagMap),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *MultiImportError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error       string                 `json:"error"`
		Ptr         *custom1.Item          `json:"ptr"`
		DetailSlice []custom2.Details      `json:"detailSlice"`
		TagMap      map[string]custom3.Tag `json:"tagMap"`
	}
	d := jsonError{Error: e.Error()}
	d.Ptr = e.Ptr
	d.DetailSlice = e.DetailSlice
	d.TagMap = e.TagMap
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *MultiImportError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Ptr         *custom1.Item          `json:"ptr"`
		DetailSlice []custom2.Details      `json:"detailSlice"`
		TagMap      map[string]custom3.Tag `json:"tagMap"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.Ptr = d.Ptr
	e.DetailSlice = d.DetailSlice
	e.TagMap = d.TagMap
	return nil
}

// NewMultiImportError creates a new MultiImportError
func NewMultiImportError(ptr *custom1.Item, detailSlice []custom2.Details, tagMap map[string]custom3.Tag) *MultiImportError {
	e := &MultiImportError{
		Ptr:         ptr,
		DetailSlice: detailSlice,
		TagMap:      tagMap,
	}
	e.onCreate()
	return e
}
