// Code generated by errgen. DO NOT EDIT.

package case2

import (
	"fmt"
	"github.com/myjupyter/errgen/test/case2_imports/custom1"
	"github.com/myjupyter/errgen/test/case2_imports/custom2"
	"github.com/myjupyter/errgen/test/case2_imports/custom3"
)

// ProcessingError is a rich error type wrapping [ErrProcessing]
type ProcessingError struct {
	Item    custom1.Item
	Mapping map[string]custom2.Details
	Tags    []custom3.Tag
}

// Error implements the error interface
func (e *ProcessingError) Error() string {
	return fmt.Sprintf("processing: item=%v, mapping=%v, tags=%v", e.Item, e.Mapping, e.Tags)
}

// Is reports whether the target matches [ErrProcessing]
func (e *ProcessingError) Is(target error) bool {
	return target == ErrProcessing
}

// Unwrap returns the underlying error(s)
func (e *ProcessingError) Unwrap() error {
	return ErrProcessing
}

// NewProcessingError creates a new ProcessingError
func NewProcessingError(item custom1.Item, mapping map[string]custom2.Details, tags []custom3.Tag) *ProcessingError {
	e := &ProcessingError{
		Item:    item,
		Mapping: mapping,
		Tags:    tags,
	}
	e.onCreate()
	return e
}

// MultiImportError is a rich error type wrapping [ErrMultiImport]
type MultiImportError struct {
	Ptr         *custom1.Item
	DetailSlice []custom2.Details
	TagMap      map[string]custom3.Tag
}

// Error implements the error interface
func (e *MultiImportError) Error() string {
	return ErrMultiImport.Error()
}

// Is reports whether the target matches [ErrMultiImport]
func (e *MultiImportError) Is(target error) bool {
	return target == ErrMultiImport
}

// Unwrap returns the underlying error(s)
func (e *MultiImportError) Unwrap() error {
	return ErrMultiImport
}

// NewMultiImportError creates a new MultiImportError
func NewMultiImportError(ptr *custom1.Item, detailSlice []custom2.Details, tagMap map[string]custom3.Tag) *MultiImportError {
	e := &MultiImportError{
		Ptr:         ptr,
		DetailSlice: detailSlice,
		TagMap:      tagMap,
	}
	e.onCreate()
	return e
}
