// Code generated by errgen. Edit this file to add custom logic.
// This file will NOT be overwritten on subsequent runs.

package case5

// onCreate is a hook for user custom logic
// the code inside must not panic
func (e *WrapSingleError) onCreate() {
	// put custom logic here
}

// onCreate is a hook for user custom logic
// the code inside must not panic
func (e *WrapTwoError) onCreate() {
	// put custom logic here
}

// onCreate is a hook for user custom logic
// the code inside must not panic
func (e *WrapChainError) onCreate() {
	// put custom logic here
}

// onCreate is a hook for user custom logic
// the code inside must not panic
func (e *WrapNoFormatError) onCreate() {
	// put custom logic here
}
