// Code generated by errgen. DO NOT EDIT.

package case5

import (
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
)

// WrapSingleError is a rich error type wrapping [ErrWrapSingle]
type WrapSingleError struct {
	Inner error
}

// Error implements the error interface
func (e *WrapSingleError) Error() string {
	return fmt.Sprintf("wrap single: %v", e.Inner)
}

// Is reports whether the target matches [ErrWrapSingle]
func (e *WrapSingleError) Is(target error) bool {
	return target == ErrWrapSingle
}

// Unwrap returns the underlying error(s)
func (e *WrapSingleError) Unwrap() []error {
	return []error{e.Inner, ErrWrapSingle}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *WrapSingleError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("inner", e.Inner),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *WrapSingleError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error string `json:"error"`
		Inner string `json:"inner,omitempty"`
	}
	d := jsonError{Error: e.Error()}
	if e.Inner != nil {
		d.Inner = e.Inner.Error()
	}
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *WrapSingleError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Inner string `json:"inner"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	if d.Inner != "" {
		e.Inner = errors.New(d.Inner)
	}
	return nil
}

// NewWrapSingleError creates a new WrapSingleError
func NewWrapSingleError(inner error) *WrapSingleError {
	e := &WrapSingleError{
		Inner: inner,
	}
	e.onCreate()
	return e
}

// WrapTwoError is a rich error type wrapping [ErrWrapTwo]
type WrapTwoError struct {
	First  error
	Second error
}

// Error implements the error interface
func (e *WrapTwoError) Error() string {
	return fmt.Sprintf("wrap two: %v, %v", e.First, e.Second)
}

// Is reports whether the target matches [ErrWrapTwo]
func (e *WrapTwoError) Is(target error) bool {
	return target == ErrWrapTwo
}

// Unwrap returns the underlying error(s)
func (e *WrapTwoError) Unwrap() []error {
	return []error{e.First, e.Second, ErrWrapTwo}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *WrapTwoError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("first", e.First),
		slog.Any("second", e.Second),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *WrapTwoError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error  string `json:"error"`
		First  string `json:"first,omitempty"`
		Second string `json:"second,omitempty"`
	}
	d := jsonError{Error: e.Error()}
	if e.First != nil {
		d.First = e.First.Error()
	}
	if e.Second != nil {
		d.Second = e.Second.Error()
	}
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *WrapTwoError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		First  string `json:"first"`
		Second string `json:"second"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	if d.First != "" {
		e.First = errors.New(d.First)
	}
	if d.Second != "" {
		e.Second = errors.New(d.Second)
	}
	return nil
}

// NewWrapTwoError creates a new WrapTwoError
func NewWrapTwoError(first error, second error) *WrapTwoError {
	e := &WrapTwoError{
		First:  first,
		Second: second,
	}
	e.onCreate()
	return e
}

// WrapChainError is a rich error type wrapping [ErrWrapChain]
type WrapChainError struct {
	Cause      error
	Underlying error
	Root       error
}

// Error implements the error interface
func (e *WrapChainError) Error() string {
	return fmt.Sprintf("wrap chain: %v -> %v -> %v", e.Cause, e.Underlying, e.Root)
}

// Is reports whether the target matches [ErrWrapChain]
func (e *WrapChainError) Is(target error) bool {
	return target == ErrWrapChain
}

// Unwrap returns the underlying error(s)
func (e *WrapChainError) Unwrap() []error {
	return []error{e.Cause, e.Underlying, e.Root, ErrWrapChain}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *WrapChainError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("cause", e.Cause),
		slog.Any("underlying", e.Underlying),
		slog.Any("root", e.Root),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *WrapChainError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error      string `json:"error"`
		Cause      string `json:"cause,omitempty"`
		Underlying string `json:"underlying,omitempty"`
		Root       string `json:"root,omitempty"`
	}
	d := jsonError{Error: e.Error()}
	if e.Cause != nil {
		d.Cause = e.Cause.Error()
	}
	if e.Underlying != nil {
		d.Underlying = e.Underlying.Error()
	}
	if e.Root != nil {
		d.Root = e.Root.Error()
	}
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *WrapChainError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Cause      string `json:"cause"`
		Underlying string `json:"underlying"`
		Root       string `json:"root"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	if d.Cause != "" {
		e.Cause = errors.New(d.Cause)
	}
	if d.Underlying != "" {
		e.Underlying = errors.New(d.Underlying)
	}
	if d.Root != "" {
		e.Root = errors.New(d.Root)
	}
	return nil
}

// NewWrapChainError creates a new WrapChainError
func NewWrapChainError(cause error, underlying error, root error) *WrapChainError {
	e := &WrapChainError{
		Cause:      cause,
		Underlying: underlying,
		Root:       root,
	}
	e.onCreate()
	return e
}

// WrapNoFormatError is a rich error type wrapping [ErrWrapNoFormat]
type WrapNoFormatError struct {
	Err error
}

// Error implements the error interface
func (e *WrapNoFormatError) Error() string {
	return ErrWrapNoFormat.Error()
}

// Is reports whether the target matches [ErrWrapNoFormat]
func (e *WrapNoFormatError) Is(target error) bool {
	return target == ErrWrapNoFormat
}

// Unwrap returns the underlying error(s)
func (e *WrapNoFormatError) Unwrap() []error {
	return []error{e.Err, ErrWrapNoFormat}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *WrapNoFormatError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("err", e.Err),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *WrapNoFormatError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error string `json:"error"`
		Err   string `json:"err,omitempty"`
	}
	d := jsonError{Error: e.Error()}
	if e.Err != nil {
		d.Err = e.Err.Error()
	}
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *WrapNoFormatError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Err string `json:"err"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	if d.Err != "" {
		e.Err = errors.New(d.Err)
	}
	return nil
}

// NewWrapNoFormatError creates a new WrapNoFormatError
func NewWrapNoFormatError(err error) *WrapNoFormatError {
	e := &WrapNoFormatError{
		Err: err,
	}
	e.onCreate()
	return e
}
