// Code generated by errgen. DO NOT EDIT.

package case5

import (
	"fmt"
	"log/slog"
)

// WrapSingleError is a rich error type wrapping [ErrWrapSingle]
type WrapSingleError struct {
	Inner error
}

// Error implements the error interface
func (e *WrapSingleError) Error() string {
	return fmt.Sprintf("wrap single: %v", e.Inner)
}

// Is reports whether the target matches [ErrWrapSingle]
func (e *WrapSingleError) Is(target error) bool {
	return target == ErrWrapSingle
}

// Unwrap returns the underlying error(s)
func (e *WrapSingleError) Unwrap() []error {
	return []error{e.Inner, ErrWrapSingle}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *WrapSingleError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("inner", e.Inner),
	)
}

// NewWrapSingleError creates a new WrapSingleError
func NewWrapSingleError(inner error) *WrapSingleError {
	e := &WrapSingleError{
		Inner: inner,
	}
	e.onCreate()
	return e
}

// WrapTwoError is a rich error type wrapping [ErrWrapTwo]
type WrapTwoError struct {
	First  error
	Second error
}

// Error implements the error interface
func (e *WrapTwoError) Error() string {
	return fmt.Sprintf("wrap two: %v, %v", e.First, e.Second)
}

// Is reports whether the target matches [ErrWrapTwo]
func (e *WrapTwoError) Is(target error) bool {
	return target == ErrWrapTwo
}

// Unwrap returns the underlying error(s)
func (e *WrapTwoError) Unwrap() []error {
	return []error{e.First, e.Second, ErrWrapTwo}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *WrapTwoError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("first", e.First),
		slog.Any("second", e.Second),
	)
}

// NewWrapTwoError creates a new WrapTwoError
func NewWrapTwoError(first error, second error) *WrapTwoError {
	e := &WrapTwoError{
		First:  first,
		Second: second,
	}
	e.onCreate()
	return e
}

// WrapChainError is a rich error type wrapping [ErrWrapChain]
type WrapChainError struct {
	Cause      error
	Underlying error
	Root       error
}

// Error implements the error interface
func (e *WrapChainError) Error() string {
	return fmt.Sprintf("wrap chain: %v -> %v -> %v", e.Cause, e.Underlying, e.Root)
}

// Is reports whether the target matches [ErrWrapChain]
func (e *WrapChainError) Is(target error) bool {
	return target == ErrWrapChain
}

// Unwrap returns the underlying error(s)
func (e *WrapChainError) Unwrap() []error {
	return []error{e.Cause, e.Underlying, e.Root, ErrWrapChain}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *WrapChainError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("cause", e.Cause),
		slog.Any("underlying", e.Underlying),
		slog.Any("root", e.Root),
	)
}

// NewWrapChainError creates a new WrapChainError
func NewWrapChainError(cause error, underlying error, root error) *WrapChainError {
	e := &WrapChainError{
		Cause:      cause,
		Underlying: underlying,
		Root:       root,
	}
	e.onCreate()
	return e
}

// WrapNoFormatError is a rich error type wrapping [ErrWrapNoFormat]
type WrapNoFormatError struct {
	Err error
}

// Error implements the error interface
func (e *WrapNoFormatError) Error() string {
	return ErrWrapNoFormat.Error()
}

// Is reports whether the target matches [ErrWrapNoFormat]
func (e *WrapNoFormatError) Is(target error) bool {
	return target == ErrWrapNoFormat
}

// Unwrap returns the underlying error(s)
func (e *WrapNoFormatError) Unwrap() []error {
	return []error{e.Err, ErrWrapNoFormat}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *WrapNoFormatError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("err", e.Err),
	)
}

// NewWrapNoFormatError creates a new WrapNoFormatError
func NewWrapNoFormatError(err error) *WrapNoFormatError {
	e := &WrapNoFormatError{
		Err: err,
	}
	e.onCreate()
	return e
}
