// Code generated by errgen. DO NOT EDIT.

package api

import (
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
)

// HTTPError is a rich error type wrapping [ErrHTTP]
type HTTPError struct {
	StatusCode int
	Message    string
}

// Error implements the error interface
func (e *HTTPError) Error() string {
	return fmt.Sprintf("HTTP %v: %v", e.StatusCode, e.Message)
}

// Is reports whether the target matches [ErrHTTP]
func (e *HTTPError) Is(target error) bool {
	return target == ErrHTTP
}

// Unwrap returns the underlying error(s)
func (e *HTTPError) Unwrap() error {
	return ErrHTTP
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *HTTPError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("statusCode", e.StatusCode),
		slog.Any("message", e.Message),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *HTTPError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error      string `json:"error"`
		StatusCode int    `json:"statusCode"`
		Message    string `json:"message"`
	}
	d := jsonError{Error: e.Error()}
	d.StatusCode = e.StatusCode
	d.Message = e.Message
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *HTTPError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		StatusCode int    `json:"statusCode"`
		Message    string `json:"message"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.StatusCode = d.StatusCode
	e.Message = d.Message
	return nil
}

// NewHTTPError creates a new HTTPError
func NewHTTPError(statusCode int, message string) *HTTPError {
	e := &HTTPError{
		StatusCode: statusCode,
		Message:    message,
	}
	e.onCreate()
	return e
}

// ValidationError is a rich error type wrapping [ErrValidation]
type ValidationError struct {
	Field        string
	WrappedError error
}

// Error implements the error interface
func (e *ValidationError) Error() string {
	return fmt.Sprintf("validation failed on '%v': %v", e.Field, e.WrappedError)
}

// Is reports whether the target matches [ErrValidation]
func (e *ValidationError) Is(target error) bool {
	return target == ErrValidation
}

// Unwrap returns the underlying error(s)
func (e *ValidationError) Unwrap() []error {
	return []error{e.WrappedError, ErrValidation}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *ValidationError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("field", e.Field),
		slog.Any("wrappedError", e.WrappedError),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *ValidationError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error        string `json:"error"`
		Field        string `json:"field"`
		WrappedError string `json:"wrappedError,omitempty"`
	}
	d := jsonError{Error: e.Error()}
	d.Field = e.Field
	if e.WrappedError != nil {
		d.WrappedError = e.WrappedError.Error()
	}
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *ValidationError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Field        string `json:"field"`
		WrappedError string `json:"wrappedError"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.Field = d.Field
	if d.WrappedError != "" {
		e.WrappedError = errors.New(d.WrappedError)
	}
	return nil
}

// NewValidationError creates a new ValidationError
func NewValidationError(field string, wrappedError error) *ValidationError {
	e := &ValidationError{
		Field:        field,
		WrappedError: wrappedError,
	}
	e.onCreate()
	return e
}
