// Code generated by errgen. DO NOT EDIT.

package api

import (
	"fmt"
)

// HTTPError is a rich error type wrapping [ErrHTTP]
type HTTPError struct {
	StatusCode int
	Message    string
}

// Error implements the error interface
func (e *HTTPError) Error() string {
	return fmt.Sprintf("HTTP %v: %v", e.StatusCode, e.Message)
}

// Is reports whether the target matches [ErrHTTP]
func (e *HTTPError) Is(target error) bool {
	return target == ErrHTTP
}

// Unwrap returns the underlying error(s)
func (e *HTTPError) Unwrap() error {
	return ErrHTTP
}

// NewHTTPError creates a new HTTPError
func NewHTTPError(statusCode int, message string) *HTTPError {
	e := &HTTPError{
		StatusCode: statusCode,
		Message:    message,
	}
	e.onCreate()
	return e
}

// ValidationError is a rich error type wrapping [ErrValidation]
type ValidationError struct {
	Field        string
	WrappedError error
}

// Error implements the error interface
func (e *ValidationError) Error() string {
	return fmt.Sprintf("validation failed on '%v': %v", e.Field, e.WrappedError)
}

// Is reports whether the target matches [ErrValidation]
func (e *ValidationError) Is(target error) bool {
	return target == ErrValidation
}

// Unwrap returns the underlying error(s)
func (e *ValidationError) Unwrap() []error {
	return []error{e.WrappedError, ErrValidation}
}

// NewValidationError creates a new ValidationError
func NewValidationError(field string, wrappedError error) *ValidationError {
	e := &ValidationError{
		Field:        field,
		WrappedError: wrappedError,
	}
	e.onCreate()
	return e
}
