// Code generated by errgen. DO NOT EDIT.

package case6

import (
	"fmt"
)

// ApplicationError is a rich error type wrapping [ErrApplication]
type ApplicationError struct {
	Code    int
	Message string
}

// Error implements the error interface
func (e *ApplicationError) Error() string {
	return fmt.Sprintf("error %v: %v", e.Code, e.Message)
}

// Is reports whether the target matches [ErrApplication]
func (e *ApplicationError) Is(target error) bool {
	return target == ErrApplication
}

// Unwrap returns the underlying error(s)
func (e *ApplicationError) Unwrap() error {
	return ErrApplication
}

// NewApplicationError creates a new ApplicationError
func NewApplicationError(code int, message string) *ApplicationError {
	e := &ApplicationError{
		Code:    code,
		Message: message,
	}
	return e
}

// InternalError is a rich error type wrapping [ErrInternal]
type InternalError struct {
	WrappedError error
}

// Error implements the error interface
func (e *InternalError) Error() string {
	return fmt.Sprintf("internal: %v", e.WrappedError)
}

// Is reports whether the target matches [ErrInternal]
func (e *InternalError) Is(target error) bool {
	return target == ErrInternal
}

// Unwrap returns the underlying error(s)
func (e *InternalError) Unwrap() []error {
	return []error{e.WrappedError, ErrInternal}
}

// NewInternalError creates a new InternalError
func NewInternalError(wrappedError error) *InternalError {
	e := &InternalError{
		WrappedError: wrappedError,
	}
	return e
}
