// Code generated by errgen. DO NOT EDIT.

package case6

import (
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
)

// ApplicationError is a rich error type wrapping [ErrApplication]
type ApplicationError struct {
	Code    int
	Message string
}

// Error implements the error interface
func (e *ApplicationError) Error() string {
	return fmt.Sprintf("error %v: %v", e.Code, e.Message)
}

// Is reports whether the target matches [ErrApplication]
func (e *ApplicationError) Is(target error) bool {
	return target == ErrApplication
}

// Unwrap returns the underlying error(s)
func (e *ApplicationError) Unwrap() error {
	return ErrApplication
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *ApplicationError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Int("code", e.Code),
		slog.String("message", e.Message),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *ApplicationError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error   string `json:"error"`
		Code    int    `json:"code"`
		Message string `json:"message"`
	}
	d := jsonError{Error: e.Error()}
	d.Code = e.Code
	d.Message = e.Message
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *ApplicationError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Code    int    `json:"code"`
		Message string `json:"message"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.Code = d.Code
	e.Message = d.Message
	return nil
}

// NewApplicationError creates a new ApplicationError
func NewApplicationError(code int, message string) *ApplicationError {
	e := &ApplicationError{
		Code:    code,
		Message: message,
	}
	return e
}

// InternalError is a rich error type wrapping [ErrInternal]
type InternalError struct {
	WrappedError error
}

// Error implements the error interface
func (e *InternalError) Error() string {
	return fmt.Sprintf("internal: %v", e.WrappedError)
}

// Is reports whether the target matches [ErrInternal]
func (e *InternalError) Is(target error) bool {
	return target == ErrInternal
}

// Unwrap returns the underlying error(s)
func (e *InternalError) Unwrap() []error {
	return []error{e.WrappedError, ErrInternal}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *InternalError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Any("wrappedError", e.WrappedError),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *InternalError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error        string `json:"error"`
		WrappedError string `json:"wrappedError,omitempty"`
	}
	d := jsonError{Error: e.Error()}
	if e.WrappedError != nil {
		d.WrappedError = e.WrappedError.Error()
	}
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *InternalError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		WrappedError string `json:"wrappedError"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	if d.WrappedError != "" {
		e.WrappedError = errors.New(d.WrappedError)
	}
	return nil
}

// NewInternalError creates a new InternalError
func NewInternalError(wrappedError error) *InternalError {
	e := &InternalError{
		WrappedError: wrappedError,
	}
	return e
}
