// Code generated by errgen. DO NOT EDIT.

package config

import (
	"fmt"
)

// NoInputFileSpecifiedError is a rich error type wrapping [ErrNoInputFileSpecified]
type NoInputFileSpecifiedError struct {
}

// Error implements the error interface
func (e *NoInputFileSpecifiedError) Error() string {
	return fmt.Sprintf("usage: errgen [flags] [source-file]")
}

// Is reports whether the target matches [ErrNoInputFileSpecified]
func (e *NoInputFileSpecifiedError) Is(target error) bool {
	return target == ErrNoInputFileSpecified
}

// Unwrap returns the underlying error(s)
func (e *NoInputFileSpecifiedError) Unwrap() error {
	return ErrNoInputFileSpecified
}

// NewNoInputFileSpecifiedError creates a new NoInputFileSpecifiedError
func NewNoInputFileSpecifiedError() *NoInputFileSpecifiedError {
	e := &NoInputFileSpecifiedError{}
	return e
}
