// Code generated by errgen. DO NOT EDIT.

package case8

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"runtime"
)

// ApplicationError is a rich error type wrapping [ErrApplication]
type ApplicationError struct {
	Code     int
	Message  string
	stackPCs []uintptr
}

// Error implements the error interface
func (e *ApplicationError) Error() string {
	return fmt.Sprintf("error %v: %v", e.Code, e.Message)
}

// Is reports whether the target matches [ErrApplication]
func (e *ApplicationError) Is(target error) bool {
	return target == ErrApplication
}

// Unwrap returns the underlying error(s)
func (e *ApplicationError) Unwrap() error {
	return ErrApplication
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *ApplicationError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Int("code", e.Code),
		slog.String("message", e.Message),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *ApplicationError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error   string `json:"error"`
		Code    int    `json:"code"`
		Message string `json:"message"`
	}
	d := jsonError{Error: e.Error()}
	d.Code = e.Code
	d.Message = e.Message
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *ApplicationError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Code    int    `json:"code"`
		Message string `json:"message"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.Code = d.Code
	e.Message = d.Message
	return nil
}

// StackTrace returns the raw program counters captured when the error was created
func (e *ApplicationError) StackTrace() []uintptr {
	return e.stackPCs
}

// StackFrames resolves the captured program counters into runtime.Frame values
func (e *ApplicationError) StackFrames() []runtime.Frame {
	if len(e.stackPCs) == 0 {
		return nil
	}
	frames := runtime.CallersFrames(e.stackPCs)
	out := make([]runtime.Frame, 0, len(e.stackPCs))
	for {
		frame, more := frames.Next()
		out = append(out, frame)
		if !more {
			break
		}
	}
	return out
}

// Format implements [fmt.Formatter]. %+v includes the captured stack trace.
func (e *ApplicationError) Format(s fmt.State, verb rune) {
	switch verb {
	case 'v':
		if s.Flag('+') {
			_, _ = io.WriteString(s, e.Error())
			for _, f := range e.StackFrames() {
				_, _ = fmt.Fprintf(s, "\n%s\n\t%s:%d", f.Function, f.File, f.Line)
			}
			return
		}
		fallthrough
	case 's':
		_, _ = io.WriteString(s, e.Error())
	case 'q':
		_, _ = fmt.Fprintf(s, "%q", e.Error())
	}
}

// NewApplicationError creates a new ApplicationError
func NewApplicationError(code int, message string) *ApplicationError {
	e := &ApplicationError{
		Code:    code,
		Message: message,
	}
	var pcs [32]uintptr
	n := runtime.Callers(2, pcs[:])
	e.stackPCs = pcs[:n]
	e.onCreate()
	return e
}

// InternalError is a rich error type wrapping [ErrInternal]
type InternalError struct {
	WrappedError error
	stackPCs     []uintptr
}

// Error implements the error interface
func (e *InternalError) Error() string {
	return fmt.Sprintf("internal: %v", e.WrappedError)
}

// Is reports whether the target matches [ErrInternal]
func (e *InternalError) Is(target error) bool {
	return target == ErrInternal
}

// Unwrap returns the underlying error(s)
func (e *InternalError) Unwrap() []error {
	return []error{e.WrappedError, ErrInternal}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *InternalError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Any("wrappedError", e.WrappedError),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *InternalError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error        string `json:"error"`
		WrappedError string `json:"wrappedError,omitempty"`
	}
	d := jsonError{Error: e.Error()}
	if e.WrappedError != nil {
		d.WrappedError = e.WrappedError.Error()
	}
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *InternalError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		WrappedError string `json:"wrappedError"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	if d.WrappedError != "" {
		e.WrappedError = errors.New(d.WrappedError)
	}
	return nil
}

// StackTrace returns the raw program counters captured when the error was created
func (e *InternalError) StackTrace() []uintptr {
	return e.stackPCs
}

// StackFrames resolves the captured program counters into runtime.Frame values
func (e *InternalError) StackFrames() []runtime.Frame {
	if len(e.stackPCs) == 0 {
		return nil
	}
	frames := runtime.CallersFrames(e.stackPCs)
	out := make([]runtime.Frame, 0, len(e.stackPCs))
	for {
		frame, more := frames.Next()
		out = append(out, frame)
		if !more {
			break
		}
	}
	return out
}

// Format implements [fmt.Formatter]. %+v includes the captured stack trace.
func (e *InternalError) Format(s fmt.State, verb rune) {
	switch verb {
	case 'v':
		if s.Flag('+') {
			_, _ = io.WriteString(s, e.Error())
			for _, f := range e.StackFrames() {
				_, _ = fmt.Fprintf(s, "\n%s\n\t%s:%d", f.Function, f.File, f.Line)
			}
			return
		}
		fallthrough
	case 's':
		_, _ = io.WriteString(s, e.Error())
	case 'q':
		_, _ = fmt.Fprintf(s, "%q", e.Error())
	}
}

// NewInternalError creates a new InternalError
func NewInternalError(wrappedError error) *InternalError {
	e := &InternalError{
		WrappedError: wrappedError,
	}
	var pcs [32]uintptr
	n := runtime.Callers(2, pcs[:])
	e.stackPCs = pcs[:n]
	e.onCreate()
	return e
}

// ForbiddenError is a rich error type wrapping [ErrForbidden]
type ForbiddenError struct {
	stackPCs []uintptr
}

// Error implements the error interface
func (e *ForbiddenError) Error() string {
	return fmt.Sprintf("forbidden")
}

// Is reports whether the target matches [ErrForbidden]
func (e *ForbiddenError) Is(target error) bool {
	return target == ErrForbidden
}

// Unwrap returns the underlying error(s)
func (e *ForbiddenError) Unwrap() error {
	return ErrForbidden
}

// StackTrace returns the raw program counters captured when the error was created
func (e *ForbiddenError) StackTrace() []uintptr {
	return e.stackPCs
}

// StackFrames resolves the captured program counters into runtime.Frame values
func (e *ForbiddenError) StackFrames() []runtime.Frame {
	if len(e.stackPCs) == 0 {
		return nil
	}
	frames := runtime.CallersFrames(e.stackPCs)
	out := make([]runtime.Frame, 0, len(e.stackPCs))
	for {
		frame, more := frames.Next()
		out = append(out, frame)
		if !more {
			break
		}
	}
	return out
}

// Format implements [fmt.Formatter]. %+v includes the captured stack trace.
func (e *ForbiddenError) Format(s fmt.State, verb rune) {
	switch verb {
	case 'v':
		if s.Flag('+') {
			_, _ = io.WriteString(s, e.Error())
			for _, f := range e.StackFrames() {
				_, _ = fmt.Fprintf(s, "\n%s\n\t%s:%d", f.Function, f.File, f.Line)
			}
			return
		}
		fallthrough
	case 's':
		_, _ = io.WriteString(s, e.Error())
	case 'q':
		_, _ = fmt.Fprintf(s, "%q", e.Error())
	}
}

// NewForbiddenError creates a new ForbiddenError
func NewForbiddenError() *ForbiddenError {
	e := &ForbiddenError{}
	var pcs [32]uintptr
	n := runtime.Callers(2, pcs[:])
	e.stackPCs = pcs[:n]
	e.onCreate()
	return e
}
