// Code generated by errgen. Edit this file to add custom logic.
// This file will NOT be overwritten on subsequent runs.

package case8

// onCreate is a hook for user custom logic
// the code inside must not panic
func (e *ApplicationError) onCreate() {
	// put custom logic here
}

// onCreate is a hook for user custom logic
// the code inside must not panic
func (e *InternalError) onCreate() {
	// put custom logic here
}

// onCreate is a hook for user custom logic
// the code inside must not panic
func (e *ForbiddenError) onCreate() {
	// put custom logic here
}
