// Code generated by errgen. DO NOT EDIT.

package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"runtime"
)

// UserNotFoundError is a rich error type wrapping [ErrUserNotFound]
type UserNotFoundError struct {
	UserID   int
	stackPCs []uintptr
}

// Error implements the error interface
func (e *UserNotFoundError) Error() string {
	return fmt.Sprintf("user %v not found", e.UserID)
}

// Is reports whether the target matches [ErrUserNotFound]
func (e *UserNotFoundError) Is(target error) bool {
	return target == ErrUserNotFound
}

// Unwrap returns the underlying error(s)
func (e *UserNotFoundError) Unwrap() error {
	return ErrUserNotFound
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *UserNotFoundError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Int("userID", e.UserID),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *UserNotFoundError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error  string `json:"error"`
		UserID int    `json:"userID"`
	}
	d := jsonError{Error: e.Error()}
	d.UserID = e.UserID
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *UserNotFoundError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		UserID int `json:"userID"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.UserID = d.UserID
	return nil
}

// StackTrace returns the raw program counters captured when the error was created
func (e *UserNotFoundError) StackTrace() []uintptr {
	return e.stackPCs
}

// StackFrames resolves the captured program counters into runtime.Frame values
func (e *UserNotFoundError) StackFrames() []runtime.Frame {
	if len(e.stackPCs) == 0 {
		return nil
	}
	frames := runtime.CallersFrames(e.stackPCs)
	out := make([]runtime.Frame, 0, len(e.stackPCs))
	for {
		frame, more := frames.Next()
		out = append(out, frame)
		if !more {
			break
		}
	}
	return out
}

// Format implements [fmt.Formatter]. %+v includes the captured stack trace.
func (e *UserNotFoundError) Format(s fmt.State, verb rune) {
	switch verb {
	case 'v':
		if s.Flag('+') {
			_, _ = io.WriteString(s, e.Error())
			for _, f := range e.StackFrames() {
				_, _ = fmt.Fprintf(s, "\n%s\n\t%s:%d", f.Function, f.File, f.Line)
			}
			return
		}
		fallthrough
	case 's':
		_, _ = io.WriteString(s, e.Error())
	case 'q':
		_, _ = fmt.Fprintf(s, "%q", e.Error())
	}
}

// NewUserNotFoundError creates a new UserNotFoundError
func NewUserNotFoundError(userID int) *UserNotFoundError {
	e := &UserNotFoundError{
		UserID: userID,
	}
	var pcs [32]uintptr
	n := runtime.Callers(2, pcs[:])
	e.stackPCs = pcs[:n]
	return e
}

// DownstreamError is a rich error type wrapping [ErrDownstream]
type DownstreamError struct {
	WrappedError error
	stackPCs     []uintptr
}

// Error implements the error interface
func (e *DownstreamError) Error() string {
	return fmt.Sprintf("downstream call failed: %v", e.WrappedError)
}

// Is reports whether the target matches [ErrDownstream]
func (e *DownstreamError) Is(target error) bool {
	return target == ErrDownstream
}

// Unwrap returns the underlying error(s)
func (e *DownstreamError) Unwrap() []error {
	return []error{e.WrappedError, ErrDownstream}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *DownstreamError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Any("wrappedError", e.WrappedError),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *DownstreamError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error        string `json:"error"`
		WrappedError string `json:"wrappedError,omitempty"`
	}
	d := jsonError{Error: e.Error()}
	if e.WrappedError != nil {
		d.WrappedError = e.WrappedError.Error()
	}
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *DownstreamError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		WrappedError string `json:"wrappedError"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	if d.WrappedError != "" {
		e.WrappedError = errors.New(d.WrappedError)
	}
	return nil
}

// StackTrace returns the raw program counters captured when the error was created
func (e *DownstreamError) StackTrace() []uintptr {
	return e.stackPCs
}

// StackFrames resolves the captured program counters into runtime.Frame values
func (e *DownstreamError) StackFrames() []runtime.Frame {
	if len(e.stackPCs) == 0 {
		return nil
	}
	frames := runtime.CallersFrames(e.stackPCs)
	out := make([]runtime.Frame, 0, len(e.stackPCs))
	for {
		frame, more := frames.Next()
		out = append(out, frame)
		if !more {
			break
		}
	}
	return out
}

// Format implements [fmt.Formatter]. %+v includes the captured stack trace.
func (e *DownstreamError) Format(s fmt.State, verb rune) {
	switch verb {
	case 'v':
		if s.Flag('+') {
			_, _ = io.WriteString(s, e.Error())
			for _, f := range e.StackFrames() {
				_, _ = fmt.Fprintf(s, "\n%s\n\t%s:%d", f.Function, f.File, f.Line)
			}
			return
		}
		fallthrough
	case 's':
		_, _ = io.WriteString(s, e.Error())
	case 'q':
		_, _ = fmt.Fprintf(s, "%q", e.Error())
	}
}

// NewDownstreamError creates a new DownstreamError
func NewDownstreamError(wrappedError error) *DownstreamError {
	e := &DownstreamError{
		WrappedError: wrappedError,
	}
	var pcs [32]uintptr
	n := runtime.Callers(2, pcs[:])
	e.stackPCs = pcs[:n]
	return e
}
