// Code generated by errgen. DO NOT EDIT.

package case9

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/myjupyter/errgen/test/case9_is_target/errcodes"
	"log/slog"
)

// InvalidUserNameError is a rich error type wrapping [ErrInvalidUserName]
type InvalidUserNameError struct {
	Name string
}

// Error implements the error interface
func (e *InvalidUserNameError) Error() string {
	return fmt.Sprintf("username '%v' is invalid", e.Name)
}

// Is reports whether the target matches [ErrInvalidUserName]
func (e *InvalidUserNameError) Is(target error) bool {
	return target == ErrInvalidUserName || target == errcodes.ErrInvalidArgument
}

// Unwrap returns the underlying error(s)
func (e *InvalidUserNameError) Unwrap() error {
	return ErrInvalidUserName
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *InvalidUserNameError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.String("name", e.Name),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *InvalidUserNameError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error string `json:"error"`
		Name  string `json:"name"`
	}
	d := jsonError{Error: e.Error()}
	d.Name = e.Name
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *InvalidUserNameError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Name string `json:"name"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.Name = d.Name
	return nil
}

// NewInvalidUserNameError creates a new InvalidUserNameError
func NewInvalidUserNameError(name string) *InvalidUserNameError {
	e := &InvalidUserNameError{
		Name: name,
	}
	return e
}

// InvalidSettingsError is a rich error type wrapping [ErrInvalidSettings]
type InvalidSettingsError struct {
}

// Error implements the error interface
func (e *InvalidSettingsError) Error() string {
	return ErrInvalidSettings.Error()
}

// Is reports whether the target matches [ErrInvalidSettings]
func (e *InvalidSettingsError) Is(target error) bool {
	return target == ErrInvalidSettings || target == errcodes.ErrInvalidArgument
}

// Unwrap returns the underlying error(s)
func (e *InvalidSettingsError) Unwrap() error {
	return ErrInvalidSettings
}

// NewInvalidSettingsError creates a new InvalidSettingsError
func NewInvalidSettingsError() *InvalidSettingsError {
	e := &InvalidSettingsError{}
	return e
}

// NotFoundUserError is a rich error type wrapping [ErrNotFoundUser]
type NotFoundUserError struct {
	ID int
}

// Error implements the error interface
func (e *NotFoundUserError) Error() string {
	return fmt.Sprintf("user with ID '%v' not found", e.ID)
}

// Is reports whether the target matches [ErrNotFoundUser]
func (e *NotFoundUserError) Is(target error) bool {
	return target == ErrNotFoundUser || target == errcodes.ErrNotFound
}

// Unwrap returns the underlying error(s)
func (e *NotFoundUserError) Unwrap() error {
	return ErrNotFoundUser
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *NotFoundUserError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Int("iD", e.ID),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *NotFoundUserError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error string `json:"error"`
		ID    int    `json:"iD"`
	}
	d := jsonError{Error: e.Error()}
	d.ID = e.ID
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *NotFoundUserError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		ID int `json:"iD"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	e.ID = d.ID
	return nil
}

// NewNotFoundUserError creates a new NotFoundUserError
func NewNotFoundUserError(iD int) *NotFoundUserError {
	e := &NotFoundUserError{
		ID: iD,
	}
	return e
}

// NotFoundSettingsError is a rich error type wrapping [ErrNotFoundSettings]
type NotFoundSettingsError struct {
}

// Error implements the error interface
func (e *NotFoundSettingsError) Error() string {
	return ErrNotFoundSettings.Error()
}

// Is reports whether the target matches [ErrNotFoundSettings]
func (e *NotFoundSettingsError) Is(target error) bool {
	return target == ErrNotFoundSettings || target == errcodes.ErrNotFound
}

// Unwrap returns the underlying error(s)
func (e *NotFoundSettingsError) Unwrap() error {
	return ErrNotFoundSettings
}

// NewNotFoundSettingsError creates a new NotFoundSettingsError
func NewNotFoundSettingsError() *NotFoundSettingsError {
	e := &NotFoundSettingsError{}
	return e
}

// UserServiceInternalError is a rich error type wrapping [ErrUserServiceInternal]
type UserServiceInternalError struct {
	Cause error
}

// Error implements the error interface
func (e *UserServiceInternalError) Error() string {
	return fmt.Sprintf("user service internal error: %v", e.Cause)
}

// Is reports whether the target matches [ErrUserServiceInternal]
func (e *UserServiceInternalError) Is(target error) bool {
	return target == ErrUserServiceInternal || target == errcodes.ErrInternal
}

// Unwrap returns the underlying error(s)
func (e *UserServiceInternalError) Unwrap() []error {
	return []error{e.Cause, ErrUserServiceInternal}
}

// LogValue implements [slog.LogValuer] for structured logging
func (e *UserServiceInternalError) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("error", e.Error()),
		slog.Any("cause", e.Cause),
	)
}

// MarshalJSON implements [json.Marshaler]
func (e *UserServiceInternalError) MarshalJSON() ([]byte, error) {
	type jsonError struct {
		Error string `json:"error"`
		Cause string `json:"cause,omitempty"`
	}
	d := jsonError{Error: e.Error()}
	if e.Cause != nil {
		d.Cause = e.Cause.Error()
	}
	return json.Marshal(d)
}

// UnmarshalJSON implements [json.Unmarshaler]
func (e *UserServiceInternalError) UnmarshalJSON(data []byte) error {
	type jsonError struct {
		Cause string `json:"cause"`
	}
	var d jsonError
	if err := json.Unmarshal(data, &d); err != nil {
		return err
	}
	if d.Cause != "" {
		e.Cause = errors.New(d.Cause)
	}
	return nil
}

// NewUserServiceInternalError creates a new UserServiceInternalError
func NewUserServiceInternalError(cause error) *UserServiceInternalError {
	e := &UserServiceInternalError{
		Cause: cause,
	}
	return e
}
